import Link from "next/link";

const columns = [
  { title: "Help", links: [["Contact", "/contact"], ["Frequently asked questions", "/faq"], ["Shipping", "/shipping"], ["Returns", "/returns"]] },
  { title: "About", links: [["Our story", "/about"], ["Build My Kit", "/build-my-kit"], ["Shop all", "/shop"], ["Contact us", "/contact"]] },
  { title: "Orders", links: [["My account", "/account"], ["Beauty profile", "/yafa"], ["Build my kit", "/build-my-kit"], ["Shop all", "/shop"]] },
] as const;

export default function Footer() {
  return <footer className="site-footer"><div className="site-footer__main"><div className="site-footer__brand"><p>YAFA VANAM</p><h2>Beauty, made personal.</h2><span>Thoughtful rituals for colour, care and scent—created for real skin and everyday life.</span></div>{columns.map((column) => <nav key={column.title} aria-label={column.title}><h3>{column.title}</h3>{column.links.map(([label, href]) => <Link key={`${label}-${href}`} href={href}>{label}</Link>)}</nav>)}<section className="site-footer__newsletter" aria-labelledby="footer-newsletter-title"><h3 id="footer-newsletter-title">Stay in touch</h3><p>New rituals, product stories and considered beauty notes.</p><form action="/contact" method="get"><label htmlFor="footer-email">Email address</label><div className="site-footer__newsletter-field"><input id="footer-email" name="email" type="email" inputMode="email" autoComplete="email" placeholder="you@example.com" required /><button type="submit">Subscribe <span aria-hidden="true">→</span></button></div></form></section></div><div className="site-footer__art" aria-hidden="true"><svg className="site-footer__botanical" viewBox="0 0 420 190" fill="none"><path d="M34 176C104 141 160 88 208 13M73 152c-5-36 7-66 34-92 9 40-2 71-34 92Zm52-42c-1-35 14-62 43-82 4 40-10 68-43 82Zm47-48c3-27 17-46 42-58-1 31-15 51-42 58Zm-72 77c29-6 55 2 78 24-35 10-62 2-78-24Zm55-47c29-3 53 8 73 32-35 7-60-4-73-32Z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></svg><p className="site-footer__art-wordmark"><span>YAFA</span><span>VANAM</span></p></div><div className="site-footer__bottom"><span>© {new Date().getFullYear()} YAFA VANAM</span><div><Link href="/privacy-policy">Privacy</Link><Link href="/cookie-policy">Cookies</Link><Link href="/terms">Terms</Link><Link href="/accessibility">Accessibility</Link></div></div></footer>;
}
