export const analyticsEvents = {
  pageViewed: "page_viewed",
  collectionViewed: "collection_viewed",
  productClicked: "product_clicked",
  productViewed: "product_viewed",
  shadeSelected: "shade_selected",
  wishlistAdded: "wishlist_added",
  productAddedToCart: "product_added_to_cart",
  productRemovedFromCart: "product_removed_from_cart",
  cartViewed: "cart_viewed",
  checkoutStarted: "checkout_started",
  shippingAdded: "shipping_added",
  paymentInfoAdded: "payment_info_added",
  purchaseCompleted: "purchase_completed",
  refundProcessed: "refund_processed",
  recommendationViewed: "recommendation_viewed",
  recommendationClicked: "recommendation_clicked",
  advisorOpened: "advisor_opened",
  advisorGoalSelected: "advisor_goal_selected",
  quizAnswered: "quiz_answered",
  imageAnalysisRequested: "image_analysis_requested",
  imageAnalysisConfirmed: "image_analysis_confirmed",
  recommendationsGenerated: "recommendations_generated",
  recommendationChanged: "recommendation_changed",
  completeLookAdded: "complete_look_added",
  variantSelected: "variant_selected",
  addToCart: "add_to_cart",
  productReturned: "product_returned",
  shadeExchangeRequested: "shade_exchange_requested",
} as const;

export type AnalyticsEventName = typeof analyticsEvents[keyof typeof analyticsEvents];
export type AnalyticsProperties = Record<string, string | number | boolean | null | undefined>;
