/**
 * Verified local product-media fallbacks. Keys use stable catalogue product IDs;
 * commerce variants remain defined exclusively in Product.json.
 */
export const makeupProductImageManifest: Record<string, string> = {
  "yv-eye-001": "/images/yafavanam/eye/mascara/fernwing/fernwing_Black_Brown.png",
  "yv-eye-002": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Black_Brown.png",
  "yv-eye-003": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Balck_Brown.png",
  "yv-eye-004": "/images/yafavanam/eye/eye%20color%20collection/eye%20canopy/Caramel_Brown.png",
  "yv-eye-005": "/images/yafavanam/eye/eye%20color%20collection/Terrastone%20Nude%20Eye%20Quad/Terrastone_Caramel_Bronze_Copper_Warm_Brown.png",
  "yv-eye-006": "/images/yafavanam/eye/eye%20color%20collection/Moonveil/Antique_Gold.png",
  "yv-eye-007": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Burgundy_Raisin.png",
  "yv-eye-008": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Burgundy_Raisin.png",
  "yv-eye-009": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Burgundy_Raisin.png",
  "yv-eye-010": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Ash_Brown.png",
  "yv-eye-011": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_ash_Brown.png",
  "yv-eye-012": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Ash_Brown.png",
  "yv-eye-013": "/images/yafavanam/eye/eye%20set%20collection/WoodLand%20Edit%20Set/Earth_Olive.png",
  "yv-eye-014": "/images/yafavanam/eye/eye%20set%20collection/MoonWood%20Eye%20Edit%20Set/Cool_Smoke_and_Plum_Story.png",
  "yv-eye-015": "/images/yafavanam/eye/eye%20set%20collection/DawnBranch%20Eye%20Wardrobe/Bridal_Gold%26Bronze_story.png",
  "yv-lip-001": "/images/yafavanam/lips/Petal-Velvet/Petal-Velvet-Berry-Soft.png",
  "yv-lip-002": "/images/yafavanam/lips/ClayRose/ClayRose_Satin_clay_rose.png",
  "yv-lip-003": "/images/yafavanam/lips/RiverRose/RiverRose-Berry-Soft.png",
  "yv-lip-004": "/images/yafavanam/lips/lipOil/lip_oil_Berry_Drop.png",
  "yv-lip-005": "/images/yafavanam/lips/Gloss/Pearlglow_Cushion_Gloss_Bronze_Pearl.png",
  "yv-lip-006": "/images/yafavanam/lips/lip_liner/lip_liner_Berry_Root.png",
  "yv-lip-007": "/images/yafavanam/lips/lip_%20staim/Lip_stain_Berry_River.png",
  "yv-lip-008": "/images/yafavanam/lips/lip_plumper/lip_Plumper_Berry_Nectar.png",
  "yv-cheek-001": "/images/yafavanam/cheeks/Airbloom/Airbloom-Dawn-Petal.png",
  "yv-cheek-002": "/images/yafavanam/cheeks/Rosemist_Blush_Liquid_Blush/Liquid_Blush_Sun_Clay.png",
  "yv-cheek-003": "/images/yafavanam/cheeks/Sunclay_cheek_Color_Cream_Blush/Cream_Blush_Rose_Mint.png",
  "yv-cheek-004": "/images/yafavanam/cheeks/cheek_tint/Cheek_tint_Clay_Bloom.png",
  "yv-cheek-005": "/images/yafavanam/cheeks/Multi-Stick/Multi-Stick-Clay-Bloom.png",
  "yv-cheek-006": "/images/yafavanam/cheeks/cheek_Balm/Cheek_balm_01_%20Petal%20Dew.png",
  "yv-complex-001": "/images/yafavanam/skin/Serum_Foundation/1C.png",
  "yv-complex-002": "/images/yafavanam/skin/Natural_Foundation/1C.png",
  "yv-complex-003": "/images/yafavanam/skin/LongWear_Foundation/1W.png",
  "yv-complex-004": "/images/yafavanam/skin/Skin_Tint/1C.png",
  "yv-complex-005": "/images/yafavanam/skin/Softcanopy_Powder_Foundation/1C.png",
  "yv-complex-006": "/images/yafavanam/skin/Underleaf%20Cover%20Concealer/1C.png",
  "yv-complex-007": "/images/yafavanam/skin/color_corrector/Color_Corrector_Apricot_Mist.png",
  "yv-complex-008": "/images/yafavanam/skin/Airveil/Airveil_Clear_Air.png",
  "yv-complex-009": "/images/yafavanam/skin/Sungrove%20Soft%20Bronzer/Sungrove_Soft_Bronzer_Deep_Terra.png",
  "yv-complex-010": "/images/yafavanam/skin/Shadowroot_Contour/Shadowroot_Contour_Deep_Hollow.png",
  "yv-complex-011": "/images/yafavanam/skin/Moonbeam_Glow_Highlighter/Moonbeam_Glow_Highlighter_Moon_Bronze.png",
  "yv-face-001": "/images/yafavanam/No%20Shades%20Items/Sun%2C%20Prep%20%26%20Finish/Petal_Veil%20_Makeup%20_Setting_Spray.png",
  "yv-face-002": "/images/yafavanam/No%20Shades%20Items/Sun%2C%20Prep%20%26%20Finish/Sunveil_Daily_Glow_Primer.png",
};
