/**
 * Verified local product/variant asset relationships. A missing entry returns
 * null so the UI never substitutes a different shade's image.
 */
const exactVariantImages: Record<string, string> = {
  "yv-cheek-001-dawn-petal": "/images/yafavanam/cheeks/Airbloom/Airbloom-Dawn-Petal.png",
  "yv-cheek-001-mauve-air": "/images/yafavanam/cheeks/Airbloom/Airbloom-Mauve-Air.png",
  "yv-cheek-001-peach-moss": "/images/yafavanam/cheeks/Airbloom/Airbloom-Peach-Moss.png",
  "yv-cheek-001-rose-mist": "/images/yafavanam/cheeks/Airbloom/Airbloom-Rose-Mist.png",
  "yv-cheek-001-soft-berry": "/images/yafavanam/cheeks/Airbloom/Airbloom-Soft-Berry.png",
  "yv-cheek-001-sun-clay": "/images/yafavanam/cheeks/Airbloom/Airbloom-Sun-Clay.png",
  "yv-cheek-002-dawn-petal": "/images/yafavanam/cheeks/Liquid_Blush/Liquid_Blush_Dawn%20Petal.png",
  "yv-cheek-002-mauve-air": "/images/yafavanam/cheeks/Liquid_Blush/Liquid_Blush_Mauve_Air.png",
  "yv-cheek-002-peach-moss": "/images/yafavanam/cheeks/Liquid_Blush/Liquid_Blush_Peach_Moss.png",
  "yv-cheek-002-rose-mist": "/images/yafavanam/cheeks/Liquid_Blush/Liquid_Blush_Rose_Mist.png",
  "yv-cheek-002-soft-berry": "/images/yafavanam/cheeks/Liquid_Blush/Liquid_Blush_Soft_Berry.png",
  "yv-cheek-002-sun-clay": "/images/yafavanam/cheeks/Liquid_Blush/Liquid_Blush_Sun_Clay.png",
  "yv-cheek-003-dawn-petal": "/images/yafavanam/cheeks/Cream_Blush/Cream_Blush_Dawn_Petal.png",
  "yv-cheek-003-mauve-air": "/images/yafavanam/cheeks/Cream_Blush/Cream_Blush_Mauve_Air.png",
  "yv-cheek-003-peach-moss": "/images/yafavanam/cheeks/Cream_Blush/Cream_Blush_Peach_Moss.png",
  "yv-cheek-003-rose-mist": "/images/yafavanam/cheeks/Cream_Blush/Cream_Blush_Rose_Mint.png",
  "yv-cheek-003-soft-berry": "/images/yafavanam/cheeks/Cream_Blush/Cream_Blush_Soft_Berry.png",
  "yv-cheek-003-sun-clay": "/images/yafavanam/cheeks/Cream_Blush/Cream_Blush_Sun_Clay.png",
  "yv-cheek-004-clay-bloom": "/images/yafavanam/cheeks/cheek_tint/Cheek_tint_Clay_Bloom.png",
  "yv-cheek-004-fern-rose": "/images/yafavanam/cheeks/cheek_tint/Cheek_tint_Fern_Rose.png",
  "yv-cheek-004-meadow-coral": "/images/yafavanam/cheeks/cheek_tint/Cheek_tint_Meadow_Coral.png",
  "yv-cheek-004-petal-dew": "/images/yafavanam/cheeks/cheek_tint/Cheek_tint_Petal_Dew.png",
  "yv-cheek-004-quiet-berry": "/images/yafavanam/cheeks/cheek_tint/Cheek_tint_Quiet_Berry.png",
  "yv-cheek-004-roseleaf": "/images/yafavanam/cheeks/cheek_tint/Cheek_tint_Roseleaf.png",
  "yv-cheek-005-clay-bloom": "/images/yafavanam/cheeks/Multi-Stick/Multi-Stick-Clay-Bloom.png",
  "yv-cheek-005-fern-rose": "/images/yafavanam/cheeks/Multi-Stick/Multi-Stick-Fern-Rose.png",
  "yv-cheek-005-meadow-coral": "/images/yafavanam/cheeks/Multi-Stick/Multi-Stick-Meadow-Coral.png",
  "yv-cheek-005-petal-dew": "/images/yafavanam/cheeks/Multi-Stick/Multi-Stick-Petal%20Dew.png",
  "yv-cheek-005-quiet-berry": "/images/yafavanam/cheeks/Multi-Stick/Multi-Stick-Quiet-Berry.png",
  "yv-cheek-005-roseleaf": "/images/yafavanam/cheeks/Multi-Stick/Multi-Stick-Roseleaf.png",
  "yv-cheek-006-clay-bloom": "/images/yafavanam/cheeks/cheekl_Balm/Cheek_Balm_05_Clay_Bloom.png",
  "yv-cheek-006-fern-rose": "/images/yafavanam/cheeks/cheekl_Balm/Cheek_Balm_06_Fern_Rose.png",
  "yv-cheek-006-meadow-coral": "/images/yafavanam/cheeks/cheekl_Balm/Cheek_Balm_03_Meadow_Coral.png",
  "yv-cheek-006-petal-dew": "/images/yafavanam/cheeks/cheekl_Balm/Cheek_balm_01_%20Petal%20Dew.png",
  "yv-cheek-006-quiet-berry": "/images/yafavanam/cheeks/cheekl_Balm/Cheek_Balm_04_Quiet_Berry.png",
  "yv-cheek-006-roseleaf": "/images/yafavanam/cheeks/cheekl_Balm/Cheek_Balm_02_Roseleaf.png",
  "yv-complex-007-apricot-mist": "/images/yafavanam/skin/color_corrector/Color_Corrector_Apricot_Mist.png",
  "yv-complex-007-butter-light": "/images/yafavanam/skin/color_corrector/Color_Corrector_Butter_Light.png",
  "yv-complex-007-lilac-air": "/images/yafavanam/skin/color_corrector/Color_Corrector_Lilac_Air.png",
  "yv-complex-007-peach-veil": "/images/yafavanam/skin/color_corrector/Color_Corrector_Peach_Veil.png",
  "yv-complex-007-sage-calm": "/images/yafavanam/skin/color_corrector/Color_Corrector_Sage_Calm.png",
  "yv-complex-008-clear-air": "/images/yafavanam/skin/Airveil/Airveil_Clear_Air.png",
  "yv-complex-008-deep-cloud": "/images/yafavanam/skin/Airveil/Airveil_Deep_Cloud.png",
  "yv-complex-008-golden-mist": "/images/yafavanam/skin/Airveil/Airveil_Golden_Mist.png",
  "yv-complex-008-soft-linen": "/images/yafavanam/skin/Airveil/Airveil_Soft_Linen.png",
  "yv-complex-009-deep-terra": "/images/yafavanam/skin/Sungrove%20Soft%20Bronzer/Sungrove_Soft_Bronzer_Deep_Terra.png",
  "yv-complex-009-golden-bark": "/images/yafavanam/skin/Sungrove%20Soft%20Bronzer/Sungrove_Soft_Bronzer_Golden_Bark.png",
  "yv-complex-009-sand-glow": "/images/yafavanam/skin/Sungrove%20Soft%20Bronzer/Sungrove_Soft_Bronzer_Sand_Glow.png",
  "yv-complex-009-sun-clay": "/images/yafavanam/skin/Sungrove%20Soft%20Bronzer/Sungrove_Soft_Bronzer_Sun_Clay.png",
  "yv-complex-009-warm-dune": "/images/yafavanam/skin/Sungrove%20Soft%20Bronzer/Sungrove_Soft_Bronzer_Warm_Dune.png",
  "yv-complex-010-deep-hollow": "/images/yafavanam/skin/Contour/Shadowroot_Contour_Deep_Hollow.png",
  "yv-complex-010-mist-shadow": "/images/yafavanam/skin/Contour/Shadowroot_Contour_Mist_shadow.png",
  "yv-complex-010-stone-branch": "/images/yafavanam/skin/Contour/Shadowroot_Contour_Stone_Branch.png",
  "yv-complex-010-taupe-root": "/images/yafavanam/skin/Contour/Shadowroot_Contour_Taupe_Root.png",
  "yv-complex-011-moon-bronze": "/images/yafavanam/skin/Highlighter/Moonbeam_Glow_Highlighter_Moon_Bronze.png",
  "yv-complex-011-pearl-haze": "/images/yafavanam/skin/Highlighter/Moonbeam_Glow_Highlighter_Pearl_Haze.png",
  "yv-complex-011-prism-petal": "/images/yafavanam/skin/Highlighter/Moonbeam_Glow_Highlighter_Prism_Petal.png",
  "yv-complex-011-soft-gold": "/images/yafavanam/skin/Highlighter/Moonbeam_Glow_Highlighter_Soft_Gold.png",
  "yv-eye-001-black-brown": "/images/yafavanam/eye/mascara/fernwing/fernwing_Black_Brown.png",
  "yv-eye-001-black-plum": "/images/yafavanam/eye/mascara/fernwing/fernwing_Black_Plum.png",
  "yv-eye-001-carbon-black": "/images/yafavanam/eye/mascara/fernwing/fernwing_Carbon_Black.png",
  "yv-eye-001-cobalt-blue": "/images/yafavanam/eye/mascara/fernwing/fernwing_Cobalt_Blue.png",
  "yv-eye-001-deep-burgundy": "/images/yafavanam/eye/mascara/fernwing/fernwing_Deep_Burgundy.png",
  "yv-eye-001-deep-violet": "/images/yafavanam/eye/mascara/fernwing/fernwing_Deep_Violet.png",
  "yv-eye-001-espresso-brown": "/images/yafavanam/eye/mascara/fernwing/fernwing_Expresso_Brown.png",
  "yv-eye-001-forest-green": "/images/yafavanam/eye/mascara/fernwing/fernwing_Forest_Green.png",
  "yv-eye-001-jet-black": "/images/yafavanam/eye/mascara/fernwing/fernwing_Jet_Black.png",
  "yv-eye-001-midnight-navy": "/images/yafavanam/eye/mascara/fernwing/fernwing_Midnight_Navy.png",
  "yv-eye-002-black-brown": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Black_Brown.png",
  "yv-eye-002-black-plum": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Black_Plum.png",
  "yv-eye-002-carbon-black": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Carbon_Black.png",
  "yv-eye-002-cobalt-blue": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Cobalt_Blue.png",
  "yv-eye-002-deep-burgundy": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Deep_Burgundy.png",
  "yv-eye-002-deep-violet": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Deep_Violet.png",
  "yv-eye-002-espresso-brown": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Expresso_Brown.png",
  "yv-eye-002-forest-green": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom__Forest_Green.png",
  "yv-eye-002-jet-black": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Jet%20Black.png",
  "yv-eye-002-midnight-navy": "/images/yafavanam/eye/mascara/night%20bloom/night_bloom_Midnight_Navy.png",
  "yv-eye-003-black-brown": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Balck_Brown.png",
  "yv-eye-003-black-plum": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Balck_Plum.png",
  "yv-eye-003-carbon-black": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Carbon_Black.png",
  "yv-eye-003-cobalt-blue": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Cobalt_Blue.png",
  "yv-eye-003-deep-burgundy": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Deep_Burgundy.png",
  "yv-eye-003-deep-violet": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Deep_Violet.png",
  "yv-eye-003-espresso-brown": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Expresso_Brown.png",
  "yv-eye-003-forest-green": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Forest_Green.png",
  "yv-eye-003-jet-black": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Jet_Black.png",
  "yv-eye-003-midnight-navy": "/images/yafavanam/eye/mascara/soft%20wing/soft_wing_Midnight_Navy.png",
  "yv-eye-007-burgundy-raisin": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Burgundy_Raisin.png",
  "yv-eye-007-charcoal": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Charcoal.png",
  "yv-eye-007-cobalt-blue": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Cobalt_Blue.png",
  "yv-eye-007-deep-chocolate": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Deep_Chocolate.png",
  "yv-eye-007-deep-indigo": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Deep_Indigo.png",
  "yv-eye-007-deep-plum": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Deep_Plum.png",
  "yv-eye-007-deep-teal": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Deep_Teal.png",
  "yv-eye-007-emerald": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Emerald.png",
  "yv-eye-007-espresso-brown": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Espresso_Brown.png",
  "yv-eye-007-kohl-black": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Kohl_Black.png",
  "yv-eye-007-smoky-bronze": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Smoky_Bronze.png",
  "yv-eye-007-violet": "/images/yafavanam/eye/eye%20liner%20collection/INKROOT%20PRECISION%20LINER/INKROOT_PRECISION_LINER_Violet.png",
  "yv-eye-008-burgundy-raisin": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Burgundy_Raisin.png",
  "yv-eye-008-charcoal": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Charcoal.png",
  "yv-eye-008-cobalt-blue": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Cobalt_Blue.png",
  "yv-eye-008-deep-chocolate": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Chocolate.png",
  "yv-eye-008-deep-indigo": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Indigo.png",
  "yv-eye-008-deep-plum": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Plum.png",
  "yv-eye-008-deep-teal": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Teal.png",
  "yv-eye-008-emerald": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Emerald.png",
  "yv-eye-008-espresso-brown": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Espresso_Brown.png",
  "yv-eye-008-kohl-black": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Kohl_Black.png",
  "yv-eye-008-smoky-bronze": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Smoky_Bronze.png",
  "yv-eye-008-violet": "/images/yafavanam/eye/eye%20liner%20collection/DEEPGROVE%20GEL%20LINER/DEEPGROVE_GEL_LINER%20_Violet.png",
  "yv-eye-009-burgundy-raisin": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Burgundy_Raisin.png",
  "yv-eye-009-charcoal": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Charcoal.png",
  "yv-eye-009-cobalt-blue": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Cobalt_Blue.png",
  "yv-eye-009-deep-chocolate": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Chocolate.png",
  "yv-eye-009-deep-indigo": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Indigo.png",
  "yv-eye-009-deep-plum": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Plum.png",
  "yv-eye-009-deep-teal": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Deep_Teal.png",
  "yv-eye-009-emerald": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Emerald.png",
  "yv-eye-009-espresso-brown": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Espresso_Brown.png",
  "yv-eye-009-kohl-black": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Kohl_Black.png",
  "yv-eye-009-smoky-bronze": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Smoky_Bronze.png",
  "yv-eye-009-violet": "/images/yafavanam/eye/eye%20liner%20collection/STORMLINE%20WATERPROOF%20LINER/DEEPGROVE_GEL_LINER%20_Violet.png",
  "yv-eye-010-ash-brown": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Ash_Brown.png",
  "yv-eye-010-ash-taupe": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Ash_Taupe.png",
  "yv-eye-010-black-brown": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Black_Brown.png",
  "yv-eye-010-neutral-deep-brown": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Neutral_Deep_Brown.png",
  "yv-eye-010-neutral-medium-brown": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Neutral_Medium.png",
  "yv-eye-010-neutral-taupe-brown": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Neutral_Taupe.png",
  "yv-eye-010-soft-black": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Soft_Black.png",
  "yv-eye-010-warm-deep-brown": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Warm_Deep.png",
  "yv-eye-010-warm-light-brown": "/images/yafavanam/eye/Brow%20collection/Briar%20Arch%20Sculpt%20Pencil/Briar_Arch_Sculpt%20Pencil_Warm_Light_Brown.png",
  "yv-eye-011-ash-brown": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_ash_Brown.png",
  "yv-eye-011-ash-taupe": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_ash_Taupe.png",
  "yv-eye-011-black-brown": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_Black_Brown.png",
  "yv-eye-011-clear": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_Clear.png",
  "yv-eye-011-neutral-deep-brown": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_Neutral_Deep_Brown.png",
  "yv-eye-011-neutral-taupe-brown": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_Neutral_Taupe.png",
  "yv-eye-011-soft-black": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_Soft_Black.png",
  "yv-eye-011-warm-deep-brown": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_Neutral_Warm_Deep_Brown.png",
  "yv-eye-011-warm-light-brown": "/images/yafavanam/eye/Brow%20collection/Willow%20Brow%20Gel/Tinted_brow_gels_Warm_light.png",
  "yv-eye-012-ash-brown": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Ash_Brown.png",
  "yv-eye-012-ash-taupe": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Ash_Taupe.png",
  "yv-eye-012-black-brown": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Black_Brown.png",
  "yv-eye-012-neutral-medium-brown": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Neutral_Medium_Brown.png",
  "yv-eye-012-neutral-taupe-brown": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Neutral_Taupe.png",
  "yv-eye-012-soft-black": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_Soft_Black.png",
  "yv-eye-012-warm-deep-brown": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Warm_Deep_Brown.png",
  "yv-eye-012-warm-light-brown": "/images/yafavanam/eye/Brow%20collection/Fernstroke%20Micro_brow%20pen/Fernstroke_Micro_brow_pen_Warm_Light_Brown.png",
  "yv-lip-001-brick-petal": "/images/yafavanam/lips/Petal-Velvet/Petal-Velvet-Brick-Petal.png",
  "yv-lip-001-petal-nude": "/images/yafavanam/lips/Petal-Velvet/Petal-Velvet-Petal-Nude.png",
  "yv-lip-002-brick-petal": "/images/yafavanam/lips/ClayRose/ClayRose_Satin__brick_petal.png",
  "yv-lip-002-petal-nude": "/images/yafavanam/lips/ClayRose/ClayRose_Satin_Petal-Nude.png",
  "yv-lip-003-petal-nude": "/images/yafavanam/lips/RiverRose/RiverRose-Petal_Nude-Brick-Red.png",
  "yv-lip-004-berry-drop": "/images/yafavanam/lips/lipOil/lip_oil_Berry_Drop.png",
  "yv-lip-004-champagne-glow": "/images/yafavanam/lips/lipOil/lip_oil_Champagne_Glow.png",
  "yv-lip-004-crystal-clear": "/images/yafavanam/lips/lipOil/lip_oil_Crystal_Clear.png",
  "yv-lip-004-golden-pearl": "/images/yafavanam/lips/lipOil/lip_oil_Golden_Peral.png",
  "yv-lip-004-honey-dew": "/images/yafavanam/lips/lipOil/lip_oil_Honey_Dew.png",
  "yv-lip-004-mauve-pearl": "/images/yafavanam/lips/lipOil/lip_oil_Mauve_Pearl.png",
  "yv-lip-004-peach-pearl": "/images/yafavanam/lips/lipOil/lip_oil_Peach_Pearl.png",
  "yv-lip-004-rose-water": "/images/yafavanam/lips/lipOil/lip_oil_Rose_Water.png",
  "yv-lip-004-shell-pink": "/images/yafavanam/lips/lipOil/lip_oil_Shell_Pink.png",
  "yv-lip-004-soft-fig": "/images/yafavanam/lips/lipOil/lip_oil_Soft_Fig.png",
  "yv-lip-005-bronze-pearl": "/images/yafavanam/lips/Gloss/Pearlglow_Cushion_Gloss_Bronze_Pearl.png",
  "yv-lip-005-champagne-glow": "/images/yafavanam/lips/Gloss/Pearlglow_Cushion_Gloss_Champagne_Glow.png",
  "yv-lip-005-mauve-pearl": "/images/yafavanam/lips/Gloss/Pearlglow_Cushion_Gloss_Mauve_Pearl.png",
  "yv-lip-005-opal-glow": "/images/yafavanam/lips/Gloss/Pearlglow_Cushion_Gloss_Opal_Glow.png",
  "yv-lip-005-pink-pearl": "/images/yafavanam/lips/Gloss/Pearlglow_Cushion_Gloss_Pink_Pearl.png",
  "yv-lip-005-rose-quartz": "/images/yafavanam/lips/Gloss/Pearlglow_Cushion_Gloss_Rose_Quartz.png",
  "yv-lip-006-berry-root": "/images/yafavanam/lips/lip_liner/lip_liner_Berry_Root.png",
  "yv-lip-006-cocoa-vine": "/images/yafavanam/lips/lip_liner/lip_liner_Cocoa_Vine.png",
  "yv-lip-006-mauve-stem": "/images/yafavanam/lips/lip_liner/lip_liner_Mauve_Stem.png",
  "yv-lip-007-berry-river": "/images/yafavanam/lips/lip_%20staim/Lip_stain_Berry_River.png",
  "yv-lip-007-brick-petal": "/images/yafavanam/lips/lip_%20staim/Lip_stain_Brick_Petal.png",
  "yv-lip-007-coral-leaf": "/images/yafavanam/lips/lip_%20staim/Lip_stain_Coral_leaf.png",
  "yv-lip-007-fig-bloom": "/images/yafavanam/lips/lip_%20staim/Lip_stain_Fig_Bloom.png",
  "yv-lip-007-plum-vine": "/images/yafavanam/lips/lip_%20staim/Lip_stain_Plum_Vine.png",
  "yv-lip-007-rose-drop": "/images/yafavanam/lips/lip_%20staim/Lip_stain_Rose_Drop.png",
  "yv-lip-008-berry-nectar": "/images/yafavanam/lips/lip_plumper/lip_Plumper_Berry_Nectar.png",
  "yv-lip-008-clear-nectar": "/images/yafavanam/lips/lip_plumper/lip_Plumper_Clear_Nectar.png",
  "yv-lip-008-nude-bloom": "/images/yafavanam/lips/lip_plumper/lip_Plumper_Nude_Bloom.png",
  "yv-lip-008-peach-honey": "/images/yafavanam/lips/lip_plumper/lip_Plumper_Peach_Honey.png",
  "yv-lip-008-soft-bronze": "/images/yafavanam/lips/lip_plumper/lip_Plumper_Soft_Bronze.png",
};

const complexionVariantFolders: Record<string, string> = {
  "yv-complex-001": "/images/yafavanam/skin/Serum_Foundation",
  "yv-complex-002": "/images/yafavanam/skin/Natural_Foundation",
  "yv-complex-003": "/images/yafavanam/skin/LongWear_Foundation",
  "yv-complex-004": "/images/yafavanam/skin/Skin_Tint",
  "yv-complex-005": "/images/yafavanam/skin/Softcanopy_Powder_Foundation",
  "yv-complex-006": "/images/yafavanam/skin/Underleaf%20Cover%20Concealer",
};

const unavailableVariantImages = new Set([
  "yv-complex-003-1c",
  "yv-complex-003-1n",
]);

export function getMakeupVariantImage(productId: string, variantId: string) {
  if (unavailableVariantImages.has(variantId)) return null;
  const exact = exactVariantImages[variantId];
  if (exact) return exact;

  const folder = complexionVariantFolders[productId];
  const shadeCode = variantId.match(/-(\d[cnwo])$/i)?.[1];
  return folder && shadeCode ? `${folder}/${shadeCode.toUpperCase()}.png` : null;
}
