"""Canonical layer: enums, normalization, and the profile/output models."""
from __future__ import annotations

from app.recommendation.canonical.enums import (
    AXIS_ALIASES,
    DEPTH_TO_INDEX,
    Daypart,
    DepthBand,
    MatchClass,
    Occasion,
    ShadeAxis,
    Undertone,
    UNSET,
    axis_for,
    depth_index_for,
)
from app.recommendation.canonical.normalization import (
    FAMILY_ALIASES,
    OCCASION_ALIASES,
    REGISTRY,
    VocabularyRegistry,
    canonical_occasion,
    family_matches,
    from_beauty_profile,
    from_v1_payload,
    normalize_list,
    normalize_token,
    to_canonical_profile,
)
from app.recommendation.canonical.schemas import (
    Candidate,
    CanonicalProfile,
    CoordinationHints,
    EngineResult,
    Recommendation,
    ShadeMatch,
    SourceRef,
)

__all__ = [
    "AXIS_ALIASES",
    "DEPTH_TO_INDEX",
    "FAMILY_ALIASES",
    "OCCASION_ALIASES",
    "REGISTRY",
    "Candidate",
    "CanonicalProfile",
    "CoordinationHints",
    "Daypart",
    "DepthBand",
    "EngineResult",
    "MatchClass",
    "Occasion",
    "Recommendation",
    "ShadeAxis",
    "ShadeMatch",
    "SourceRef",
    "UNSET",
    "Undertone",
    "VocabularyRegistry",
    "axis_for",
    "canonical_occasion",
    "depth_index_for",
    "family_matches",
    "from_beauty_profile",
    "from_v1_payload",
    "normalize_list",
    "normalize_token",
    "to_canonical_profile",
]
