"""Generate a portable SQL seed file from the YAFA VANAM catalogue.

Driver-free alternative to import_catalogue.py: emits idempotent upserts against
the apps/api/db/migrations schema as plain SQL you can pipe into psql, e.g.

    python seed_database.py --out catalogue_seed.sql
    docker compose exec -T postgres psql -U postgres -d yafa_vanam < catalogue_seed.sql

Row identity matches import_catalogue.py (same deterministic UUIDs), so the two
paths produce interchangeable data.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from import_catalogue import (  # noqa: E402
    CATEGORY_COLUMNS,
    DEFAULT_CATALOGUE,
    IMAGE_COLUMNS,
    PRODUCT_COLUMNS,
    SHADE_COLUMNS,
    VARIANT_COLUMNS,
    build_rows,
    upsert_sql,
)
from validate_catalogue import validate_catalogue  # noqa: E402


class Raw(str):
    """A pre-rendered SQL fragment emitted verbatim instead of as a literal."""


def sql_literal(value: Any) -> str:
    if isinstance(value, Raw):
        return str(value)
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def jsonb_literal(value: Any) -> Raw:
    payload = json.dumps(value, ensure_ascii=False)
    tag = "$json$"
    while tag in payload:
        tag += "x"
    return Raw(f"{tag}{payload}{tag}::jsonb")


def render_insert(table: str, columns: list[str], conflict: list[str], row: dict[str, Any]) -> str:
    placeholders = ", ".join(sql_literal(row.get(column)) for column in columns)
    statement = f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})"
    updates = ", ".join(
        f"{column} = EXCLUDED.{column}" for column in columns if column not in ("id", *conflict)
    )
    if updates:
        statement += f" ON CONFLICT ({', '.join(conflict)}) DO UPDATE SET {updates}, updated_at = NOW()"
    else:
        statement += f" ON CONFLICT ({', '.join(conflict)}) DO NOTHING"
    return statement + ";"


def render_sql(rows: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        "-- Generated by data/scripts/seed_database.py; do not edit by hand.",
        "BEGIN;",
        "",
    ]
    parents = [row for row in rows["categories"] if row["parent_id"] is None]
    children = [row for row in rows["categories"] if row["parent_id"] is not None]
    lines.append("-- categories")
    lines.extend(render_insert("categories", CATEGORY_COLUMNS, ["slug"], row)
                 for row in [*parents, *children])
    lines.append("")
    lines.append("-- products")
    for row in rows["products"]:
        seeded = {**row, "benefits": jsonb_literal(row["benefits"])}
        lines.append(render_insert("products", PRODUCT_COLUMNS, ["slug"], seeded))
    lines.append("")
    lines.append("-- shades")
    lines.extend(render_insert("shades", SHADE_COLUMNS, ["product_id", "slug"], row)
                 for row in rows["shades"])
    lines.append("")
    lines.append("-- product_variants")
    lines.extend(render_insert("product_variants", VARIANT_COLUMNS, ["sku"], row)
                 for row in rows["variants"])
    lines.append("")
    lines.append("-- product_images (replaced wholesale for imported products)")
    product_ids = ", ".join(sql_literal(row["id"]) for row in rows["products"])
    lines.append(f"DELETE FROM product_images WHERE product_id IN ({product_ids});")
    lines.extend(
        "INSERT INTO product_images ({columns}) VALUES ({values});".format(
            columns=", ".join(IMAGE_COLUMNS),
            values=", ".join(sql_literal(row.get(column)) for column in IMAGE_COLUMNS),
        )
        for row in rows["images"]
    )
    lines.extend(["", "COMMIT;", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a PostgreSQL seed file from the catalogue.")
    parser.add_argument("--catalogue", default=str(DEFAULT_CATALOGUE), help="normalized catalogue JSON")
    parser.add_argument("--out", help="output .sql path (default: stdout)")
    parser.add_argument("--force", action="store_true", help="generate even when validation reports errors")
    args = parser.parse_args(argv)

    catalogue_path = Path(args.catalogue)
    try:
        with catalogue_path.open("r", encoding="utf-8") as handle:
            products = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cannot read catalogue {catalogue_path}: {exc}")

    findings = validate_catalogue(products)
    errors = [f for f in findings if f.severity == "error"]
    for finding in findings:
        print(f"[{finding.severity.upper()}] {finding.location}: {finding.message}", file=sys.stderr)
    if errors and not args.force:
        raise SystemExit(f"{len(errors)} validation error(s); fix them or pass --force")

    rows = build_rows(products)
    sql = render_sql(rows)

    if args.out:
        Path(args.out).write_text(sql, encoding="utf-8")
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(sql)
    print(f"seed covers {len(rows['categories'])} categories, {len(rows['products'])} products, "
          f"{len(rows['shades'])} shades, {len(rows['variants'])} variants, {len(rows['images'])} images",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
