"use client";
import { useEffect, useRef, useState } from "react";

type Props = { open: boolean; onClose: () => void; onLogin: (email: string, password: string, remember: boolean) => Promise<void>; onRegister: (name: string, email: string, password: string, remember: boolean) => Promise<void>; googleUrl: string };
export default function AuthModal({ open, onClose, onLogin, onRegister, googleUrl }: Props) {
  const [mode, setMode] = useState<"signin" | "signup">("signin"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const key = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", key); document.body.style.overflow = "hidden"; dialog.current?.focus(); return () => { document.removeEventListener("keydown", key); document.body.style.overflow = ""; }; }, [open, onClose]);
  if (!open) return null;
  const submit = async (form: HTMLFormElement) => { const data = new FormData(form); const password = String(data.get("password") || ""); if (mode === "signup" && password !== String(data.get("confirmPassword") || "")) { setError("Passwords do not match."); return; } setBusy(true); setError(""); try { if (mode === "signin") await onLogin(String(data.get("email")), password, data.get("remember") === "on"); else await onRegister(String(data.get("name")), String(data.get("email")), password, data.get("remember") === "on"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to continue."); } finally { setBusy(false); } };
  return <div className="auth-modal__backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="auth-modal" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="auth-title" tabIndex={-1}><button className="auth-modal__close" type="button" onClick={onClose} aria-label="Close sign in">×</button><p className="auth-modal__eyebrow">YOUR YAFA VANAM RITUAL</p><h2 id="auth-title">{mode === "signin" ? "Welcome back" : "Create your account"}</h2><div className="auth-modal__tabs"><button className={mode === "signin" ? "is-active" : ""} type="button" onClick={() => { setMode("signin"); setError(""); }}>Sign in</button><button className={mode === "signup" ? "is-active" : ""} type="button" onClick={() => { setMode("signup"); setError(""); }}>Sign up</button></div><form onSubmit={(event) => { event.preventDefault(); void submit(event.currentTarget); }}>
    {mode === "signup" && <label>Full name<input name="name" autoComplete="name" required /></label>}<label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" minLength={8} autoComplete={mode === "signin" ? "current-password" : "new-password"} required /></label>{mode === "signup" && <label>Confirm password<input name="confirmPassword" type="password" minLength={8} autoComplete="new-password" required /></label>}<div className="auth-modal__options"><label className="auth-modal__remember"><input name="remember" type="checkbox" /> Remember me</label>{mode === "signin" && <button type="button" className="auth-modal__link">Forgot password?</button>}</div>{error && <p className="auth-modal__error" role="alert">{error}</p>}<button className="auth-modal__submit" disabled={busy} type="submit">{busy ? "Please wait…" : mode === "signin" ? "Sign in" : "Create account"}</button>
  </form><div className="auth-modal__divider"><span>or</span></div><a className="auth-modal__google" href={googleUrl}><span aria-hidden="true">G</span> Continue with Google</a><p className="auth-modal__fineprint">Secure checkout begins after you sign in. You can continue browsing freely.</p></section></div>;
}
